# -*- coding: utf-8 -*-
from . import contact_custom
from . import contracts
from . import contact_relation_type
from . import documents_custom
from . import document_types
from . import service_types
from . import service_request
from . import expense_types
from . import service_workflow_config
from . import contact_payment
from . import service_request_workflow
from . import payment_transaction
from . import res_config_settings_custom
from . import res_company_custom
from . import contact_address
from . import contact_emergency
from . import contact_passport
from . import contact_ikama
from . import country_region
from . import country_kaza
from . import contact_religion
from . import news
from . import website_info
from . import circular_event_meeting
from . import website_feedback
from . import ambassador_greetings
from . import job_vacancies
from . import ebs_partner_socialmedia
from . import ebs_enroll_requests
from . import hr_job
